let p = Promise.resolve(new Error("Algo deu errado"));

console.log("Outros cÃ³digos");

console.log(p);

p.then((value) => console.log(value))
   .catch((reason) => {console.log(`Erro: ${reason}`)});